interface Description {
    type: number;
    key: string;
    name: string;
}

interface Configuration {
    languages: Array<Description>;
    game: Array<Description>;
    cluster: Array<Description>;
    mixing: Array<Description>;
    traits: Array<Description>;
    geyser: Array<Description>;
}

const configuration: Configuration = {
    languages: [
        { type: 0, key: "en", name: "English" },
        { type: 1, key: "zh-CN", name: "简体中文" },
    ],
    game: [
        { type: 0, key: "", name: "Base Game" },
        { type: 1, key: "", name: "Classic" },
        { type: 2, key: "", name: "Spaced Out!" },
    ],
    cluster: [
        { type: 0, key: "SNDST-A", name: "Terra" },
        { type: 0, key: "OCAN-A", name: "Oceania" },
        { type: 0, key: "S-FRZ", name: "Rime" },
        { type: 0, key: "LUSH-A", name: "Verdante" },
        { type: 0, key: "FRST-A", name: "Arboria" },
        { type: 0, key: "VOLCA", name: "Volcanea" },
        { type: 0, key: "BAD-A", name: "The Badlands" },
        { type: 0, key: "HTFST-A", name: "Aridio" },
        { type: 0, key: "OASIS-A", name: "Oasisse" },
        { type: 0, key: "CER-A", name: "Ceres" },
        { type: 0, key: "CERS-A", name: "Blasted Ceres" },
        { type: 0, key: "PRE-A", name: "Relica" },
        { type: 0, key: "PRES-A", name: "RelicAAAAGH" },
        { type: 1, key: "V-SNDST-C", name: "Terra Cluster" },
        { type: 1, key: "V-OCAN-C", name: "Oceania Cluster" },
        { type: 1, key: "V-SWMP-C", name: "Squelchy Cluster" },
        { type: 1, key: "V-SFRZ-C", name: "Rime Cluster" },
        { type: 1, key: "V-LUSH-C", name: "Verdante Cluster" },
        { type: 1, key: "V-FRST-C", name: "Arboria Cluster" },
        { type: 1, key: "V-VOLCA-C", name: "Volcanea Cluster" },
        { type: 1, key: "V-BAD-C", name: "The Badlands Cluster" },
        { type: 1, key: "V-HTFST-C", name: "Aridio Cluster" },
        { type: 1, key: "V-OASIS-C", name: "Oasisse Cluster" },
        { type: 1, key: "V-CER-C", name: "Ceres Cluster" },
        { type: 1, key: "V-CERS-C", name: "Blasted Ceres Cluster" },
        { type: 1, key: "V-PRE-C", name: "Relica Cluster" },
        { type: 1, key: "V-PRES-C", name: "RelicAAAAGH Cluster" },
        { type: 2, key: "SNDST-C", name: "Terrania Cluster" },
        { type: 2, key: "PRE-C", name: "Relica Minor Cluster" },
        { type: 2, key: "CER-C", name: "Ceres Minor Cluster" },
        { type: 2, key: "FRST-C", name: "Folia Cluster" },
        { type: 2, key: "SWMP-C", name: "Quagmiris Cluster" },
        { type: 2, key: "M-SWMP-C", name: "Moonlet Cluster - Metallic Swampy" },
        { type: 2, key: "M-BAD-C", name: "Moonlet Cluster - The Desolands" },
        { type: 2, key: "M-FRZ-C", name: "Moonlet Cluster - Frozen Forest" },
        { type: 2, key: "M-FLIP-C", name: "Moonlet Cluster - Flipped" },
        // prettier-ignore
        { type: 2, key: "M-RAD-C", name: "Moonlet Cluster - Radioactive Ocean", },
        { type: 2, key: "M-CERS-C", name: "Moonlet Cluster - Ceres Mantle" },
    ],
    mixing: [
        { type: 10, key: "d2p1", name: "The Frosty Planet Pack" },
        { type: 6, key: "d2f1", name: "Ceres Fragment" },
        { type: 9, key: "d2b1", name: "Ice Cave Biome" },
        { type: 8, key: "d2b2", name: "Cool Pool Biome" },
        { type: 7, key: "d2b3", name: "Nectar Biome" },
        { type: 5, key: "d3p1", name: "The Bionic Booster Pack" },
        { type: 4, key: "d4p1", name: "The Prehistoric Planet Pack" },
        { type: 0, key: "d4f1", name: "Relica Fragment" },
        { type: 3, key: "d4b1", name: "Garden Biome" },
        { type: 2, key: "d4b2", name: "Feather Biome" },
        { type: 1, key: "d4b3", name: "Wetlands Biome" },
    ],
    geyser: [
        { type: 1, key: "steam", name: "Cool Steam Vent" },
        { type: 0, key: "hot_steam", name: "Steam Vent" },
        { type: 1, key: "hot_water", name: "Water Geyser" },
        { type: 1, key: "slush_water", name: "Cool Slush Geyser" },
        { type: 1, key: "filthy_water", name: "Polluted Water Vent" },
        { type: 1, key: "slush_salt_water", name: "Cool Salt Slush Geyser" },
        { type: 1, key: "salt_water", name: "Salt Water Geyser" },
        { type: 0, key: "small_volcano", name: "Minor Volcano" },
        { type: 0, key: "big_volcano", name: "Volcano" },
        { type: 2, key: "liquid_co2", name: "Carbon Dioxide Geyser" },
        { type: 2, key: "hot_co2", name: "Carbon Dioxide Vent" },
        { type: 2, key: "hot_hydrogen", name: "Hydrogen Vent" },
        { type: 2, key: "hot_po2", name: "Hot Polluted Oxygen Vent" },
        { type: 2, key: "slimy_po2", name: "InFectious Polluted Oxygen Vent" },
        { type: 2, key: "chlorine_gas", name: "Chlorine Gas Vent" },
        { type: 0, key: "methane", name: "Natural Gas Geyser" },
        { type: 0, key: "molten_copper", name: "Copper Volcano" },
        { type: 0, key: "molten_iron", name: "Iron Volcano" },
        { type: 0, key: "molten_gold", name: "Gold Volcano" },
        { type: 0, key: "molten_aluminum", name: "Aluminum Volcano" },
        { type: 0, key: "molten_cobalt", name: "Cobalt Volcano" },
        { type: 0, key: "oil_drip", name: "Leaky Oil Fissure" },
        { type: 0, key: "liquid_sulfur", name: "Liquid Sulfur Geyser" },
        { type: 0, key: "chlorine_gas_cool", name: "Cool Chlorine Gas Vent" },
        { type: 0, key: "molten_tungsten", name: "Tungsten Volcano" },
        { type: 0, key: "molten_niobium", name: "Niobium Volcano" },
        { type: 0, key: "printpod", name: "Printing Pod" },
        { type: 0, key: "oil_reservoir", name: "Oil Reservoir" },
        { type: 0, key: "receiver", name: "Supply Teleporter Output" },
        { type: 0, key: "sender", name: "Supply Teleporter Input" },
        { type: 0, key: "teleporter", name: "Teleporter Transmitter" },
        { type: 0, key: "cryopod", name: "Cryotank 3000" },
    ],
    traits: [
        { type: 0, key: "", name: "No Traits" },
        { type: 0, key: "", name: "Crashed Satellites" },
        { type: 0, key: "", name: "Frozen Friend" },
        { type: 0, key: "", name: "Irregular Oil" },
        { type: 0, key: "", name: "Lush Core" },
        { type: 0, key: "", name: "Metallic Caves" },
        { type: 0, key: "", name: "Radioactive Crust" },
        { type: 0, key: "", name: "Subsurface Ocean" },
        { type: 0, key: "", name: "Volcanic Activity" },
        { type: 2, key: "", name: "Large Boulders" },
        { type: 0, key: "", name: "Medium Boulders" },
        { type: 2, key: "", name: "Mixed Boulders" },
        { type: 0, key: "", name: "Small Boulders" },
        { type: 0, key: "", name: "Trapped Oil" },
        { type: 0, key: "", name: "Frozen Core" },
        { type: 1, key: "", name: "Geoactive" },
        { type: 1, key: "", name: "Geodes" },
        { type: 2, key: "", name: "Geodormant" },
        { type: 0, key: "", name: "Large Claciers" },
        { type: 0, key: "", name: "Irregular Oil" },
        { type: 0, key: "", name: "Magma Channels" },
        { type: 2, key: "", name: "Metal Poor" },
        { type: 1, key: "", name: "Metal Rich" },
        { type: 0, key: "", name: "Alternate Pod Location" },
        { type: 0, key: "", name: "Slime Molds" },
        { type: 0, key: "", name: "Subsurface Ocean" },
        { type: 0, key: "", name: "Volcanic Activity" },
    ],
};

export default configuration;
